const product = {
    _id: String,
    title: String,
    price: Number,
    size: Number,
    brand: String,
    condition: String,
    gender: String,
    stock: Number,
    size_desc: String,
    shoes_desc: String,
    images: Array,
}



export const products = [
    {
        _id: '1',
        title: 'Hoka Product 1',
        price: 3104,
        size: 27,
        brand: 'hoka',
        condition: 'premium',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 27 / UK 21 / US 25',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '2',
        title: 'Adidas Product 2',
        price: 3249,
        size: 21,
        brand: 'adidas',
        condition: 'premium',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 21 / UK 16 / US 19',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '3',
        title: 'Fila Product 3',
        price: 4588,
        size: 47,
        brand: 'fila',
        condition: 'excellent',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 47 / UK 37 / US 43',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '4',
        title: 'Adidas Product 4',
        price: 10903,
        size: 37,
        brand: 'adidas',
        condition: 'premium',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 37 / UK 29 / US 34',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '5',
        title: 'Asics Product 5',
        price: 3629,
        size: 48,
        brand: 'asics',
        condition: 'very good',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 48 / UK 38 / US 44',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '6',
        title: 'Converse Product 6',
        price: 7795,
        size: 32,
        brand: 'converse',
        condition: 'premium',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 32 / UK 25 / US 29',
        shoes_desc: 'Converse Chuck Taylor is a timeless icon with endless versatility.'
    },
    {
        _id: '7',
        title: 'Fila Product 7',
        price: 19496,
        size: 44,
        brand: 'fila',
        condition: 'premium',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 44 / UK 35 / US 40',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '8',
        title: 'Puma Product 8',
        price: 5553,
        size: 31,
        brand: 'puma',
        condition: 'very good',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 31 / UK 24 / US 28',
        shoes_desc: 'Puma sneakers offer modern style paired with all-day comfort.'
    },
    {
        _id: '9',
        title: 'Asics Product 9',
        price: 8631,
        size: 33,
        brand: 'asics',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 33 / UK 26 / US 30',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '10',
        title: 'Saucony Product 10',
        price: 17529,
        size: 21,
        brand: 'saucony',
        condition: 'premium',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 21 / UK 16 / US 19',
        shoes_desc: 'Saucony combines durability with lightweight performance, perfect for an active lifestyle.'
    },
    {
        _id: '11',
        title: 'Fila Product 11',
        price: 1668,
        size: 21,
        brand: 'fila',
        condition: 'very good',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 21 / UK 16 / US 19',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '12',
        title: 'Fila Product 12',
        price: 18892,
        size: 31,
        brand: 'fila',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 31 / UK 24 / US 28',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '13',
        title: 'Hoka Product 13',
        price: 19642,
        size: 28,
        brand: 'hoka',
        condition: 'premium+',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 28 / UK 22 / US 26',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '14',
        title: 'Nike Product 14',
        price: 17879,
        size: 28,
        brand: 'nike',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 28 / UK 22 / US 26',
        shoes_desc: 'Nike provides innovation in every step, delivering style and performance.'
    },
    {
        _id: '15',
        title: 'Asics Product 15',
        price: 3703,
        size: 36,
        brand: 'asics',
        condition: 'premium',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 36 / UK 28 / US 33',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '16',
        title: 'Saucony Product 16',
        price: 8283,
        size: 44,
        brand: 'saucony',
        condition: 'premium+',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 44 / UK 35 / US 40',
        shoes_desc: 'Saucony combines durability with lightweight performance, perfect for an active lifestyle.'
    },
    {
        _id: '17',
        title: 'Nike Product 17',
        price: 10536,
        size: 37,
        brand: 'nike',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 37 / UK 29 / US 34',
        shoes_desc: 'Nike provides innovation in every step, delivering style and performance.'
    },
    {
        _id: '18',
        title: 'Fila Product 18',
        price: 1595,
        size: 26,
        brand: 'fila',
        condition: 'premium+',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 26 / UK 20 / US 24',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '19',
        title: 'Vans Product 19',
        price: 19421,
        size: 44,
        brand: 'vans',
        condition: 'premium',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 44 / UK 35 / US 40',
        shoes_desc: 'Vans blends skate-inspired aesthetics with superior durability.'
    },
    {
        _id: '20',
        title: 'Converse Product 20',
        price: 1020,
        size: 19,
        brand: 'converse',
        condition: 'excellent',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 19 / UK 15 / US 18',
        shoes_desc: 'Converse Chuck Taylor is a timeless icon with endless versatility.'
    },
    {
        _id: '21',
        title: 'Adidas Product 21',
        price: 10550,
        size: 42,
        brand: 'adidas',
        condition: 'excellent',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 42 / UK 33 / US 38',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '22',
        title: 'Converse Product 22',
        price: 2494,
        size: 42,
        brand: 'converse',
        condition: 'excellent',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 42 / UK 33 / US 38',
        shoes_desc: 'Converse Chuck Taylor is a timeless icon with endless versatility.'
    },
    {
        _id: '23',
        title: 'Hoka Product 23',
        price: 5267,
        size: 26,
        brand: 'hoka',
        condition: 'excellent',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 26 / UK 20 / US 24',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '24',
        title: 'Puma Product 24',
        price: 3769,
        size: 26,
        brand: 'puma',
        condition: 'very good',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 26 / UK 20 / US 24',
        shoes_desc: 'Puma sneakers offer modern style paired with all-day comfort.'
    },
    {
        _id: '25',
        title: 'Vans Product 25',
        price: 2324,
        size: 44,
        brand: 'vans',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 44 / UK 35 / US 40',
        shoes_desc: 'Vans blends skate-inspired aesthetics with superior durability.'
    },
    {
        _id: '26',
        title: 'Hoka Product 26',
        price: 6344,
        size: 23,
        brand: 'hoka',
        condition: 'premium',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 23 / UK 18 / US 21',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '27',
        title: 'Adidas Product 27',
        price: 11737,
        size: 21,
        brand: 'adidas',
        condition: 'premium+',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 21 / UK 16 / US 19',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '28',
        title: 'Converse Product 28',
        price: 4884,
        size: 22,
        brand: 'converse',
        condition: 'premium',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 22 / UK 17 / US 20',
        shoes_desc: 'Converse Chuck Taylor is a timeless icon with endless versatility.'
    },
    {
        _id: '29',
        title: 'Hoka Product 29',
        price: 17028,
        size: 43,
        brand: 'hoka',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 43 / UK 34 / US 39',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '30',
        title: 'Adidas Product 30',
        price: 5317,
        size: 48,
        brand: 'adidas',
        condition: 'very good',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 48 / UK 38 / US 44',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '31',
        title: 'Asics Product 31',
        price: 13883,
        size: 41,
        brand: 'asics',
        condition: 'premium+',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 41 / UK 32 / US 37',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '32',
        title: 'Vans Product 32',
        price: 1242,
        size: 27,
        brand: 'vans',
        condition: 'very good',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 27 / UK 21 / US 25',
        shoes_desc: 'Vans blends skate-inspired aesthetics with superior durability.'
    },
    {
        _id: '33',
        title: 'Hoka Product 33',
        price: 2378,
        size: 29,
        brand: 'hoka',
        condition: 'excellent',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 29 / UK 23 / US 27',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '34',
        title: 'Hoka Product 34',
        price: 8460,
        size: 36,
        brand: 'hoka',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 36 / UK 28 / US 33',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '35',
        title: 'Nike Product 35',
        price: 2500,
        size: 48,
        brand: 'nike',
        condition: 'premium+',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 48 / UK 38 / US 44',
        shoes_desc: 'Nike provides innovation in every step, delivering style and performance.'
    },
    {
        _id: '36',
        title: 'Converse Product 36',
        price: 8752,
        size: 32,
        brand: 'converse',
        condition: 'very good',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 32 / UK 25 / US 29',
        shoes_desc: 'Converse Chuck Taylor is a timeless icon with endless versatility.'
    },
    {
        _id: '37',
        title: 'Hoka Product 37',
        price: 6905,
        size: 48,
        brand: 'hoka',
        condition: 'premium',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 48 / UK 38 / US 44',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '38',
        title: 'Nike Product 38',
        price: 12239,
        size: 37,
        brand: 'nike',
        condition: 'excellent',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 37 / UK 29 / US 34',
        shoes_desc: 'Nike provides innovation in every step, delivering style and performance.'
    },
    {
        _id: '39',
        title: 'Adidas Product 39',
        price: 13880,
        size: 23,
        brand: 'adidas',
        condition: 'premium+',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 23 / UK 18 / US 21',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '40',
        title: 'Hoka Product 40',
        price: 12940,
        size: 41,
        brand: 'hoka',
        condition: 'very good',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 41 / UK 32 / US 37',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '41',
        title: 'Asics Product 41',
        price: 16998,
        size: 32,
        brand: 'asics',
        condition: 'excellent',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 32 / UK 25 / US 29',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '42',
        title: 'Nike Product 42',
        price: 3256,
        size: 39,
        brand: 'nike',
        condition: 'excellent',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 39 / UK 31 / US 36',
        shoes_desc: 'Nike provides innovation in every step, delivering style and performance.'
    },
    {
        _id: '43',
        title: 'Fila Product 43',
        price: 18315,
        size: 39,
        brand: 'fila',
        condition: 'premium+',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 39 / UK 31 / US 36',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '44',
        title: 'Hoka Product 44',
        price: 11169,
        size: 39,
        brand: 'hoka',
        condition: 'premium',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 39 / UK 31 / US 36',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '45',
        title: 'Adidas Product 45',
        price: 6536,
        size: 47,
        brand: 'adidas',
        condition: 'premium',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 47 / UK 37 / US 43',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '46',
        title: 'Hoka Product 46',
        price: 10325,
        size: 41,
        brand: 'hoka',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 41 / UK 32 / US 37',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '47',
        title: 'Asics Product 47',
        price: 2846,
        size: 20,
        brand: 'asics',
        condition: 'very good',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 20 / UK 16 / US 18',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '48',
        title: 'Asics Product 48',
        price: 15778,
        size: 44,
        brand: 'asics',
        condition: 'excellent',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 44 / UK 35 / US 40',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '49',
        title: 'Fila Product 49',
        price: 15925,
        size: 21,
        brand: 'fila',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 21 / UK 16 / US 19',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '50',
        title: 'Vans Product 50',
        price: 6933,
        size: 20,
        brand: 'vans',
        condition: 'excellent',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 20 / UK 16 / US 18',
        shoes_desc: 'Vans blends skate-inspired aesthetics with superior durability.'
    },
    {
        _id: '51',
        title: 'Adidas Product 51',
        price: 5242,
        size: 48,
        brand: 'adidas',
        condition: 'premium+',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 48 / UK 38 / US 44',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '52',
        title: 'Asics Product 52',
        price: 13620,
        size: 33,
        brand: 'asics',
        condition: 'excellent',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 33 / UK 26 / US 30',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '53',
        title: 'Vans Product 53',
        price: 1315,
        size: 35,
        brand: 'vans',
        condition: 'premium+',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 35 / UK 28 / US 32',
        shoes_desc: 'Vans blends skate-inspired aesthetics with superior durability.'
    },
    {
        _id: '54',
        title: 'Saucony Product 54',
        price: 1142,
        size: 46,
        brand: 'saucony',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 46 / UK 36 / US 42',
        shoes_desc: 'Saucony combines durability with lightweight performance, perfect for an active lifestyle.'
    },
    {
        _id: '55',
        title: 'Puma Product 55',
        price: 14985,
        size: 19,
        brand: 'puma',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 19 / UK 15 / US 18',
        shoes_desc: 'Puma sneakers offer modern style paired with all-day comfort.'
    },
    {
        _id: '56',
        title: 'Puma Product 56',
        price: 14491,
        size: 22,
        brand: 'puma',
        condition: 'premium+',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 22 / UK 17 / US 20',
        shoes_desc: 'Puma sneakers offer modern style paired with all-day comfort.'
    },
    {
        _id: '57',
        title: 'Asics Product 57',
        price: 19543,
        size: 25,
        brand: 'asics',
        condition: 'premium+',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 25 / UK 20 / US 23',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '58',
        title: 'Converse Product 58',
        price: 9949,
        size: 33,
        brand: 'converse',
        condition: 'premium',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 33 / UK 26 / US 30',
        shoes_desc: 'Converse Chuck Taylor is a timeless icon with endless versatility.'
    },
    {
        _id: '59',
        title: 'Adidas Product 59',
        price: 3029,
        size: 24,
        brand: 'adidas',
        condition: 'excellent',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 24 / UK 19 / US 22',
        shoes_desc: 'Adidas Ultraboost and NMD series merge energy return with a sleek design.'
    },
    {
        _id: '60',
        title: 'Fila Product 60',
        price: 11126,
        size: 45,
        brand: 'fila',
        condition: 'very good',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 45 / UK 36 / US 41',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '61',
        title: 'Nike Product 61',
        price: 16058,
        size: 39,
        brand: 'nike',
        condition: 'premium+',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 39 / UK 31 / US 36',
        shoes_desc: 'Nike provides innovation in every step, delivering style and performance.'
    },
    {
        _id: '62',
        title: 'Vans Product 62',
        price: 14142,
        size: 46,
        brand: 'vans',
        condition: 'excellent',
        collection: 'women',
        stock: 1,
        size_desc: 'EUR 46 / UK 36 / US 42',
        shoes_desc: 'Vans blends skate-inspired aesthetics with superior durability.'
    },
    {
        _id: '63',
        title: 'Puma Product 63',
        price: 2171,
        size: 36,
        brand: 'puma',
        condition: 'premium+',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 36 / UK 28 / US 33',
        shoes_desc: 'Puma sneakers offer modern style paired with all-day comfort.'
    },
    {
        _id: '64',
        title: 'Hoka Product 64',
        price: 13907,
        size: 32,
        brand: 'hoka',
        condition: 'excellent',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 32 / UK 25 / US 29',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '65',
        title: 'Asics Product 65',
        price: 4920,
        size: 35,
        brand: 'asics',
        condition: 'excellent',
        collection: 'kids',
        stock: 1,
        size_desc: 'EUR 35 / UK 28 / US 32',
        shoes_desc: 'Asics Gel series offers unmatched support and cushioning, tailored for runners of all levels.'
    },
    {
        _id: '66',
        title: 'Converse Product 66',
        price: 19968,
        size: 44,
        brand: 'converse',
        condition: 'premium',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 44 / UK 35 / US 40',
        shoes_desc: 'Converse Chuck Taylor is a timeless icon with endless versatility.'
    },
    {
        _id: '67',
        title: 'Fila Product 67',
        price: 4087,
        size: 28,
        brand: 'fila',
        condition: 'excellent',
        collection: 'men',
        stock: 1,
        size_desc: 'EUR 28 / UK 22 / US 26',
        shoes_desc: 'Fila Athletic shoes combine sporty design with everyday comfort, making them ideal for active lifestyles.'
    },
    {
        _id: '68',
        title: 'Hoka Product 68',
        price: 8667,
        size: 30,
        brand: 'hoka',
        condition: 'excellent',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 30 / UK 24 / US 27',
        shoes_desc: 'Hoka shoes are engineered for maximum cushioning and minimal weight, ideal for long-distance runners.'
    },
    {
        _id: '69',
        title: 'Vans Product 69',
        price: 6230,
        size: 23,
        brand: 'vans',
        condition: 'premium',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 23 / UK 18 / US 21',
        shoes_desc: 'Vans blends skate-inspired aesthetics with superior durability.'
    },
    {
        _id: '70',
        title: 'Saucony Product 70',
        price: 7522,
        size: 19,
        brand: 'saucony',
        condition: 'premium+',
        collection: 'unisex',
        stock: 1,
        size_desc: 'EUR 19 / UK 15 / US 18',
        shoes_desc: 'Saucony combines durability with lightweight performance, perfect for an active lifestyle.'
    }
]